name: Airbyte Integration Test

on:
  push:
    branches:
      - main

jobs:
  airbyte-integration-test:
    runs-on: ubuntu-latest  # You can choose the desired runner platform

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      # install requirements
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Airbyte Installation
        run: |
          git clone --depth=1 https://github.com/airbytehq/airbyte.git

      - name: Install Octavia cli
        run: |
          bash ./octavia_installer.sh

      - name: Start Airbyte in Background
        run: |
          ./airbyte/run-ab-platform.sh &
          sleep 240

      # https://stackoverflow.com/questions/72981949/github-actions-how-to-share-bash-aliases-across-steps
      - name: Enable Alias sharing
        run: |
          rc=/tmp/rcfile
          echo 'shopt -s expand_aliases' > $rc
          echo 'alias octavia="docker run -i --rm -v \$(pwd):/home/octavia-project --network host --user root:root airbyte/octavia-cli:0.44.4"' >> $rc

      - name: Initialize octavia project
        run: |
          source /tmp/rcfile
          mkdir octavia
          cd octavia && octavia init

      - name: Deploy octavia
        env:
          # https://stackoverflow.com/questions/60176044/how-do-i-use-an-env-file-with-github-actions
          AZURE_BLOB_STORAGE_KEY: ${{ secrets.AZURE_BLOB_STORAGE_KEY }}
        run: |
          echo $AZURE_BLOB_STORAGE_KEY > ~/.env
          export OCTAVIA_ENV_FILE=~/.env
          source /tmp/rcfile
          sudo ./copy_template_files.sh
          cd octavia && octavia apply --force
      - name: Always destroy .env OCTAVIA_ENV_FILE
        run: rm ~/.env
        if: always()

      - name: Trigger manual synchronization
        run: python manually_trigger_sync.py
