name: Airbyte Integration Test

on:
  push:
    branches:
      - main

jobs:
  airbyte-integration-test:
    runs-on: ubuntu-latest  # You can choose the desired runner platform

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Airbyte Installation
        run: |
          git clone --depth=1 https://github.com/airbytehq/airbyte.git

      - name: Airbyte Startup in Background
        run: |

      - name: Install Octavia cli
        run: |
          bash ./octavia_installer.sh
          source /home/runner/.bashrc

      - name: Initialize octavia project
        run: |
          mkdir octavia
          cd octavia
          shopt -s expand_aliases 
          alias octavia="docker run -i --rm -v \$(pwd):/home/octavia-project --network host --user root:root airbyte/octavia-cli:0.44.4"
          ../airbyte/run-ab-platform.sh &
          sleep 240
          octavia init

      - name: Test octavia
        run: |
          octavia list connectors destinations | grep Azure
