name: Airbyte Integration Test

on:
  push:
    branches:
      - main

jobs:
  airbyte-integration-test:
    runs-on: ubuntu-latest  # You can choose the desired runner platform

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Airbyte Installation
        run: |
          git clone --depth=1 https://github.com/airbytehq/airbyte.git

      - name: Airbyte Startup in Background
        run: |
          cd airbyte
          ./run-ab-platform.sh &

      - name: Install Octavia cli
        run: |
          curl -s -o- https://raw.githubusercontent.com/airbytehq/airbyte/master/octavia-cli/install.sh | bash

      - name: Initialize octavia project
        run: |
          mkdir octavia
          cd octavia
          octavia init

      - name: Test octavia
        run: |
          octavia list connectors destinations | grep Azure
